name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        java-version: "11"
        architecture: "x64"
        distribution: "temurin"
    - name: Check formatting
      run: 
        ./mill --no-server --disable-ticker mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
    - name: Check scalafix
      run: 
        ./mill --no-server --disable-ticker __.fix --check
    - name: Compile
      run: 
        ./mill --no-server --disable-ticker __.compile
    - name: Publish Artifacts
      run: 
        ./mill --no-server --disable-ticker __.publishArtifacts
    - name: Test
      run:
        ./mill --no-server --disable-ticker __.test
  publish-sonatype:
    if: github.repository == 'Eleven19/keep-a-changelog' && (contains(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch')
    needs: build
    runs-on: ubuntu-22.04
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.ELEVEN19_IO_PGP_SECRET_BASE64 }}
      SONATYPE_USER: ${{ secrets.ELEVEN19_SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.ELEVEN19_SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          architecture: "x64"
          distribution: "temurin"
      - name: Publish to Maven Central
        run: ./mill -i io.kipp.mill.ci.release.ReleaseModule/publishAll
        env:
          PGP_PASSPHRASE: ${{ secrets.ELEVEN19_IO_PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.ELEVEN19_IO_PGP_SECRET_BASE64 }}
          SONATYPE_PASSWORD: ${{ secrets.ELEVEN19_SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.ELEVEN19_SONATYPE_USERNAME }}