name: ci

on:
  push:
    branches: ["main"]
    tags: ['*']
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache packages
      uses: coursier/cache-action@v6
      id: coursier-cache

    - uses: actions/setup-java@v4
      with:
        java-version: "11"
        architecture: "x64"
        distribution: "temurin"
    - name: Check formatting
      run: 
        ./mill --no-server --disable-ticker mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
    - name: Check scalafix
      run: 
        ./mill --no-server --disable-ticker __.fix --check
    - name: Compile
      run: 
        ./mill --no-server --disable-ticker __.compile
    - name: Publish Artifacts
      run: 
        ./mill --no-server --disable-ticker __.publishArtifacts
    - name: Test
      run:
        ./mill --no-server --disable-ticker __.test
        
  publish-release:
    if: github.repository == 'Eleven19/keep-a-changelog' && (contains(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.ELEVEN19_IO_PGP_SECRET_BASE64 }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.ELEVEN19_IO_PGP_PASSPHRASE }}
      SONATYPE_USER: ${{ secrets.ELEVEN19_SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.ELEVEN19_SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: coursier/cache-action@v6
        id: coursier-cache

      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          architecture: "x64"
          distribution: "temurin"

      - name: Setup For Release (i.e. GPG)
        run: ./mill -i mill.local.plugins.ci.release.ReleaseSetupModule/setup

      - name: Publish to Maven Central
        run: |
          ./mill --no-server --disable-ticker mill.contrib.sonatypecentral.SonatypeCentralPublishModule/publishAll \
              --username $SONATYPE_USER \
              --password $SONATYPE_PASSWORD \
              --gpgArgs --passphrase=$SONATYPE_PGP_PRIVATE_KEY_PASSWORD,--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b \
              --publishArtifacts __.publishArtifacts \
              --readTimeout 600000 \
              --awaitTimeout 600000 \
              --connectionTimeout 600000 \
              --shouldRelease true \
              --bundleName io.eleven19.keep-a-changelog:$GITHUB_SHA

      - name: Publish release from tag
        uses: ghalactic/github-release-from-tag@v5
        with:
          generateReleaseNotes: "true"
          prerelease: "false"
          draft: "false"